### PR TITLE
Updated to add support for overwriting an existing test run.

### PR DESCRIPTION
**Pull request by almightyfoon**
Added the following flag:

	--update-existing-run
	
This flag will check for a run with the same name as the one provided and will update that run instead of creating a new one.
It will also add results to a testrun that were not part of the test run.

### CODE REVIEW

**Comment by almightyfoon** [comment]
Still some kinks to be worked out. Its not working like I was expecting, false positives with the tests I was doing. Will reopen once it actually works.

**Comment by dubner** [comment]
@almightyfoon Let me know how you get on, would be nice to see your work merged.

**Comment by almightyfoon** [comment]
Will do. I've got a few more features to add like some more error handling and a flag to close the run once its finished.

**Comment by almightyfoon** [comment]
I've also updated the requests requirements.

**Comment by apallier** [comment]
FYI, I am merging PR #25 containing a very close feature. I'll normally finish in few days.

**Comment by dubner** [comment]
Don't think this PR is longer required due to https://github.com/dubner/pytest-testrail/pull/25 being merged.

**Comment by Igur007** [comment]
Will this request be fixed and merged? some useful things are done....

**Comment by apallier** [comment]
@Igur007 This feature has been implemented in PR#25. This PR is already merged.

**Comment by Igur007** [comment]
@apallier That was a new option in code of this request "--close-on-complete" and I can't find it merged. Does another option exist?

**Comment by apallier** [comment]
@Igur007 Sorry, I did not see this PR implements an other option than "--update-existing-run". I think the better way is to use your PR#36 to manage a "testrun closing" feature. I am not the maintainer of this repo but I think it should be easier to merge.

**Comment by dubner** [comment]
@Igur007  this PR is quite outdated now, are you planning on fixing it up if there is anything left to implement ? or can it be closed ?

**Comment by allankp** [comment]
Closing this PR, way out of data and believe no longer required.

**Pull request closed without merging**
